title: joaoepj.github.io
#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default"
